server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 362778057123-9ldskh834854tjpal6vnvb3hn78henfu.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 735872737940022
            client-secret: 0ea91e14df553a05ff32dafc3d184bcf
            scope:
            - email
            - public_profile
          naver:
            client-id: 2d0kaneuUgYKN3iTPpeq
            client-secret: XWao0_XfhI
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/naver
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.

debug: true
    
          